export const MOVIES = [
  {
    id: '11-star-wars',
    title: 'Star Wars',
    photo:
      'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
  },
  {
    id: '12-finding-nemo',
    title: 'Finding Nemo',
    photo:
      'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg',
  },
  {
    id: '11006-smokey-and-the-bandit',
    title: 'Smokey and the Bandit',
    photo:
      'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/vKEUp6L57RMGHMdC0hdCJiVyEW6.jpg',
  },
  {
    id: '9340-the-goonies',
    title: 'The Goonies',
    photo:
      'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/eBU7gCjTCj9n2LTxvCSIXXOvHkD.jpg',
  },
]

export const ANIMALS = [
  { id: '1', name: 'Penguin' },
  { id: '2', name: 'Otter' },
  { id: '3', name: 'Panda' },
  { id: '4', name: 'Koala' },
  { id: '5', name: 'Polar Bear' },
  { id: '6', name: 'Puppy' },
  { id: '7', name: 'Kitten' },
  { id: '8', name: 'Monkey' },
  { id: '9', name: 'Sloth' },
  { id: '10', name: 'Turtle' },
  { id: '11', name: 'Elephant' },
  { id: '12', name: 'Giraffe' },
  { id: '13', name: 'Lion' },
  { id: '14', name: 'Tiger' },
  { id: '15', name: 'Zebra' },
  { id: '16', name: 'Hippo' },
  { id: '17', name: 'Rhino' },
  { id: '18', name: 'Gorilla' },
  { id: '19', name: 'Pig' },
  { id: '20', name: 'Cow' },
  { id: '21', name: 'Horse' },
  { id: '22', name: 'Sheep' },
  { id: '23', name: 'Duck' },
  { id: '24', name: 'Chicken' },
  { id: '25', name: 'Turkey' },
  { id: '26', name: 'Dinosaur' },
  { id: '27', name: 'Dragon' },
  { id: '28', name: 'Unicorn' },
  { id: '29', name: 'Snail' },
  { id: '30', name: 'Bee' },
  { id: '31', name: 'Butterfly' },
  { id: '32', name: 'Ladybug' },
  { id: '33', name: 'Rabbit' },
  { id: '34', name: 'Frog' },
  { id: '35', name: 'Deer' },
  { id: '36', name: 'Bear' },
  { id: '37', name: 'Fox' },
  { id: '38', name: 'Wolf' },
  { id: '39', name: 'Shark' },
  { id: '40', name: 'Whale' },
  { id: '41', name: 'Dolphin' },
  { id: '42', name: 'Seagull' },
  { id: '43', name: 'Bald Eagle' },
  { id: '44', name: 'Owl' },
  { id: '45', name: 'Parrot' },
  { id: '46', name: 'Flamingo' },
  { id: '47', name: 'Pigeon' },
  { id: '48', name: 'Squirrel' },
  { id: '49', name: 'Chipmunk' },
  { id: '50', name: 'Mouse' },
]

export const COLORS = [
  { id: '1', name: 'red' },
  { id: '2', name: 'orange' },
  { id: '3', name: 'yellow' },
  { id: '4', name: 'green' },
  { id: '5', name: 'blue' },
  { id: '6', name: 'purple' },
  { id: '7', name: 'pink' },
  { id: '8', name: 'brown' },
  { id: '9', name: 'black' },
  { id: '10', name: 'white' },
  { id: '11', name: 'gray' },
  { id: '12', name: 'rainbow' },
  { id: '13', name: 'gold' },
  { id: '14', name: 'teal' },
  { id: '15', name: 'turquoise' },
  { id: '16', name: 'indigo' },
  { id: '17', name: 'violet' },
  { id: '18', name: 'magenta' },
  { id: '19', name: 'lime' },
  { id: '20', name: 'sky blue' },
]

export const ACTIVITIES = [
  { id: '1', name: 'Rides a roller coaster' },
  { id: '2', name: 'Goes to the beach' },
  { id: '3', name: 'Goes to the zoo' },
  { id: '4', name: 'Goes to the aquarium' },
  { id: '5', name: 'Goes to the museum' },
  { id: '6', name: 'First day of school' },
  { id: '7', name: 'Goes to the park' },
  { id: '8', name: 'Goes to the movies' },
  { id: '9', name: 'Goes to a concert' },
  { id: '10', name: 'Celebrates a birthday party' },
  { id: '11', name: 'Cooks a meal for friends' },
  { id: '12', name: 'Goes shopping for new shoes' },
  { id: '13', name: 'Goes to a baseball game' },
  { id: '14', name: 'Goes to a football game' },
  { id: '15', name: 'Goes to a basketball game' },
  { id: '16', name: 'Goes to a soccer game' },
  { id: '17', name: 'Goes to a hockey game' },
  { id: '18', name: 'Goes to a tennis match' },
  { id: '19', name: 'Writes a song' },
  { id: '20', name: 'Writes a poem' },
  { id: '21', name: 'Paints a picture' },
  { id: '22', name: 'Goes to a dance recital' },
  { id: '23', name: 'Acts in a play' },
  { id: '24', name: 'Learns to play piano' },
  { id: '24', name: 'Learns to play guitar' },
  { id: '25', name: 'Learns to play drums' },
]
